### ISSUE TITLE
Unit Funktionen anhand von inventar festlegen,

### ISSUE THREAD

**Issue by Shockwave52** [TDC-Clan/A3-MissionTemplate#18]
Pio/Sani funktionen klappen nur mit der entsprechenden Unit. Entweder in Template jeweils eine unit pro trupp oder workaround: Medic-Kit oder Toolkit abfragen und sobald das im Inventar ist die Unit als Pio/Sani festlegen, wär ganz cool.

**Comment by TDC-Insane** [comment]
AGM + DB = Win
Arbeite an sowas
